---
# Download and install CloudWatch Agent
- name: Install CloudWatch Agent
  apt:
    name: amazon-cloudwatch-agent
    state: present

# Start CloudWatch Agent
- name: Start CloudWatch Agent
  service:
    name: amazon-cloudwatch-agent
    state: started
    enabled: yes

# Optional: Configure CloudWatch Agent (if you have a config file)
- name: Copy CloudWatch config file
  copy:
    src: ./config.json
    dest: /opt/aws/amazon-cloudwatch-agent/bin/config.json
    owner: root
    group: root
    mode: 0644

# Optional: Run CloudWatch Agent with the config
- name: Start CloudWatch Agent with config
  command: /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a start -c file:/opt/aws/amazon-cloudwatch-agent/bin/config.json
